# Generated by Django 5.2.4 on 2025-08-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_code',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
