# Generated by Django 5.2.4 on 2025-08-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qr_profile_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
