# Generated by Django 5.2.4 on 2025-08-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='org_logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logo/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_upload',
            field=models.ImageField(blank=True, help_text='Used when uploading manually', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='Used when signing up with Google', max_length=500, null=True),
        ),
    ]
