# Generated by Django 5.2.4 on 2025-08-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='org_logo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture_upload',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://ik.imagekit.io/cafedejur/sari-sari-events/default-profile.jpg?updatedAt=1753685867575', max_length=500, null=True),
        ),
    ]
