# Generated by Django 5.2.4 on 2025-09-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_customuser_org_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='org_logo',
            field=models.ImageField(blank=True, default='defaults/default-logo.png', null=True, upload_to=''),
        ),
    ]
