# Generated by Django 5.2.4 on 2025-09-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_customuser_org_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='org_logo',
            field=models.ImageField(default='defaults/default-logo.png', upload_to=''),
        ),
    ]
