# Generated by Django 5.2.4 on 2025-09-09 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_customuser_org_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subaccounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('admin', 'Admin'), ('staff', 'Staff')], default='organizer', max_length=20),
        ),
    ]
