# Generated by Django 5.2.4 on 2025-09-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_customuser_added_by_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_code',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
