# Generated by Django 5.2.4 on 2025-09-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_customuser_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('co-organizer', 'Co-Organizer'), ('admin', 'Admin'), ('staff', 'Staff')], default='organizer', max_length=20),
        ),
    ]
