# Generated by Django 5.2.4 on 2025-09-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('co-organizer', 'Co-Organizer'), ('admin', 'Admin'), ('staff', 'Staff'), ('user', 'User')], default='organizer', max_length=20),
        ),
    ]
