# Generated by Django 5.2.4 on 2025-09-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='org_logo',
            field=models.ImageField(default='defaults/default-logo.png', upload_to='profile_logo/'),
        ),
    ]
