# Generated by Django 5.2.4 on 2025-08-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_type',
            name='seating_map',
        ),
        migrations.AddField(
            model_name='event',
            name='seating_map',
            field=models.ImageField(blank=True, null=True, upload_to='event/seating_maps/'),
        ),
    ]
