# Generated by Django 5.2.4 on 2025-08-16 01:08

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_ticket_type_seating_map_event_seating_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_poster',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.unique_event_poster_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='seating_map',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.unique_seating_map_path),
        ),
    ]
