# Generated by Django 5.2.4 on 2025-08-23 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_category_alter_event_event_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_form_template',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_form_templates', to='events.event', to_field='event_code'),
        ),
    ]
