# Generated by Django 5.2.4 on 2025-08-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_reg_form_template_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='collect_email',
            field=models.CharField(choices=[('collect', 'Collect'), ('do-not-collect', 'Do not collect')], default='collect', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_specific',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
