# Generated by Django 5.2.4 on 2025-08-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_collect_email_event_venue_specific'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_broadcast',
            field=models.CharField(choices=[('broadcast', 'Broadcast'), ('do-not-broadcast', 'Do not broadcast')], default='broadcast', max_length=20),
        ),
    ]
