# Generated by Django 5.2.4 on 2025-09-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_form_question',
            name='allow_specific_types',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='reg_form_question',
            name='file_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reg_form_question',
            name='max_file_size',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='reg_form_question',
            name='max_files',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='reg_form_question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('short', 'Short'), ('long', 'Long'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('rating', 'Rating'), ('file-upload', 'File Upload')], default='short', max_length=20, null=True),
        ),
    ]
