# Generated by Django 5.2.4 on 2025-09-23 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_reg_form_question_allow_specific_types_and_more'),
        ('subscriptions', '0002_subscription_payment_subscription_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='events.event'),
        ),
    ]
