# Generated by Django 5.2.4 on 2025-08-14 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_name', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('dti_registration_number', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=50)),
                ('business_address', models.TextField()),
                ('dti_file', models.FileField(upload_to='organizer_documents/dti/')),
                ('govt_id_file', models.FileField(upload_to='organizer_documents/govt_id/')),
                ('business_permit_file', models.FileField(upload_to='organizer_documents/business_permit/')),
                ('tin_file', models.FileField(upload_to='organizer_documents/tin/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
