# Generated by Django 5.2.4 on 2025-09-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='related_event',
            new_name='event',
        ),
    ]
