# Generated by Django 5.2.4 on 2025-08-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('event', models.CharField(max_length=255)),
                ('reg_date', models.DateField()),
                ('ticket_type', models.CharField(max_length=100)),
            ],
        ),
    ]
