# Generated by Django 5.2.4 on 2025-08-26 06:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
        ('events', '0005_alter_reg_form_template_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='name',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='reg_date',
        ),
        migrations.AddField(
            model_name='attendee',
            name='attendee_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='attendee_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('checked-in', 'Checked-in')], default='registered', max_length=100),
        ),
        migrations.AddField(
            model_name='attendee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendee',
            name='price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='ticket_qr_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='ticket_qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='event/qr_codes/'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.event', to_field='event_code'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.ticket_type'),
        ),
        migrations.CreateModel(
            name='Attendee_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='attendees.attendee')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='events.reg_form_question')),
                ('selection_option_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='events.question_option')),
            ],
        ),
    ]
