# Generated by Django 5.2.4 on 2025-08-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0002_rename_name_attendee_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
