# Generated by Django 5.2.4 on 2025-08-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0004_attendee_contactnumber_alter_attendee_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee_response',
            name='selection_option_id',
        ),
    ]
