# Generated by Django 5.2.4 on 2025-08-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0005_remove_attendee_response_selection_option_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='ticket_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
