# Generated by Django 5.2.4 on 2025-08-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0006_attendee_ticket_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='contactNumber',
        ),
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='ticket_qr_data',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='ticket_qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='event/attendees_qr/'),
        ),
    ]
