# Generated by Django 5.2.4 on 2025-08-30 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0007_remove_attendee_contactnumber_alter_attendee_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendees.attendee', to_field='attendee_code')),
                ('checked_in_by_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_in_attendances', to=settings.AUTH_USER_MODEL, to_field='user_code')),
            ],
        ),
    ]
