# Generated by Django 5.2.4 on 2025-08-30 08:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0008_event_attendance'),
        ('events', '0008_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_attendance',
            name='event',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_attendees', to='events.event', to_field='event_code'),
            preserve_default=False,
        ),
    ]
