# Generated by Django 5.2.4 on 2025-08-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0009_event_attendance_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_attendance',
            name='event',
        ),
    ]
