# Generated by Django 5.2.4 on 2025-09-02 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0010_remove_event_attendance_event'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendees', to='transactions.transaction'),
        ),
    ]
