# Generated by Django 5.2.4 on 2025-09-02 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0011_attendee_transaction'),
        ('transactions', '0002_rename_related_event_transaction_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='transactions.transaction', to_field='payment_ref'),
        ),
    ]
