# Generated by Django 5.2.4 on 2025-09-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0012_alter_attendee_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='fullName',
        ),
        migrations.AddField(
            model_name='attendee',
            name='firstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attendee',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
