# Generated by Django 5.2.4 on 2025-09-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0013_remove_attendee_fullname_attendee_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='firstname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
    ]
