# Generated by Django 5.2.4 on 2025-09-12 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0014_alter_attendee_firstname_alter_attendee_lastname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_attendance',
            name='checked_in_by_organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_in_attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
