name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and build React frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Copy React build to Django static folder
        run: |
          rm -rf backend/static/*
          cp -r frontend/build/* backend/static/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Zip project for deployment
        run: |
          zip -r deploy.zip * .[^.]*

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: YOUR_EB_APP_NAME
          environment_name: YOUR_EB_ENV_NAME
          version_label: v-${{ github.run_number }}-${{ github.sha }}
          region: ap-southeast-1
          deployment_package: deploy.zip
